add_newline = false

# Explicitly define the prompt layout: Arrow -> Path -> Git -> %
format = "$character$directory$git_branch$git_status$custom[% ](bold blue)"

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ ](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
# Letting the terminal theme handle the color
style = "bold"

[git_branch]
symbol = ""
style = "bold blue"
format = "[\\($branch]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)[\\)](bold blue) "
style = "bold green"
modified = "[✭](green)"
untracked = "[✱](cyan)"
staged = "[✚](yellow)"
deleted = "[✗](red)"
renamed = "[➦](blue)"
conflicted = "[✂](magenta)"

# [custom.npm_linked]
# command = "ls -F node_modules | grep '@$' && echo '@'"
# detect_files = ["package.json"]
# style = "bold 13"
# format = "[$output]($style) "

# Disable language modules that cause the "via" text
[lua]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
